### ISSUE TITLE
Проверять существование обработок

### ISSUE THREAD

**Issue by alehinsasha** [silverbulleters/vanessa-stack-commons#1]
Т.к. обработки будут использоваться программно, а так же планируется переименование/перемещение обработок, нужно проверять их существование.

**Comment by alehinsasha** [comment]
По совету знатоков путь к обработкам будет определяться относительно каталога "stack commons" а путь до этого каталога нужно будет указывать в форме своей обработки.

**Comment by allustin** [comment]
Залинковал задачи в связанном инструментарии, чтобы реализовать такое поведение

**Comment by alehinsasha** [comment]
Готово
